# Generated by Django 4.1.3 on 2023-01-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone', models.CharField(max_length=10)),
                ('Address', models.CharField(max_length=100)),
                ('Faculty', models.CharField(max_length=50)),
            ],
        ),
    ]
