# Generated by Django 4.1.3 on 2022-12-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('marks', models.IntegerField()),
                ('passed_date', models.DateField()),
            ],
        ),
    ]
