# Generated by Django 4.1.3 on 2022-12-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('College', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.IntegerField(unique=True)),
                ('address', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
