# Generated by Django 4.1.3 on 2022-12-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_student_address_student_email_student_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Faculty',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
    ]
