# Generated by Django 4.1.3 on 2022-12-28 03:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=100)),
                ('sdur', models.IntegerField()),
                ('singer', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
