# Generated by Django 4.1.3 on 2023-01-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=70)),
                ('post_cat', models.CharField(max_length=70)),
                ('post_desc', models.CharField(max_length=600)),
                ('post_pdate', models.DateField()),
            ],
        ),
    ]
